project_id = "hhnycprummorizjvzyrw"

[functions.sitemap-xml]
verify_jwt = false

[functions.upload-image-webp]
verify_jwt = false

[functions.ai-search]
verify_jwt = false

[functions.wholesale-lead]
verify_jwt = false

[functions.abandoned-cart-save]
verify_jwt = false

[functions.abandoned-cart-recover]
verify_jwt = false

[functions.seo-landing-generate]
verify_jwt = true

[functions.ai-quick-import]
verify_jwt = true

[functions.repeat-order-cron]
verify_jwt = false

[functions.seo-landing-batch]
verify_jwt = true
